# Generated by Django 2.1.1 on 2018-09-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_myuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executor', to='accounts.MyUser')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager', to='accounts.MyUser')),
            ],
        ),
    ]
